'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const template = fs.readFileSync(path.join(root, 'site.template.html'), 'utf8');
const viewer = fs.readFileSync(path.join(root, 'viewer.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');

for (const html of [template, viewer]) {
  assert.match(html, /id="lightboxMobileSearchToggle"[\s\S]*?class="viewer-control-separator"[\s\S]*?id="fitHeightBtn"/);
  assert.doesNotMatch(html, /id="viewerLayoutToggle"/);
  assert.doesNotMatch(html, /viewer-layout-icon-(?:scroll|side)/);
  assert.match(html, /id="viewerScrollPages"[^>]*role="list"/);
}

assert.match(app, /const VIEWER_LAYOUT_SIDE = "side";/);
assert.match(app, /const VIEWER_LAYOUT_SCROLL = "scroll";/);
assert.match(app, /viewerLayoutMode: VIEWER_LAYOUT_SCROLL/);
assert.match(app, /const requiredMode = favoritesMode \? VIEWER_LAYOUT_SIDE : VIEWER_LAYOUT_SCROLL;/);
assert.match(app, /state\.viewerLayoutMode = source === LIGHTBOX_SOURCE_FAVORITES[\s\S]*?\? VIEWER_LAYOUT_SIDE[\s\S]*?: VIEWER_LAYOUT_SCROLL/);
assert.doesNotMatch(app, /VIEWER_LAYOUT_STORAGE_KEY|readViewerLayoutPreference|writeViewerLayoutPreference/);
assert.doesNotMatch(app, /viewerLayoutToggle|toggleViewerLayoutMode|setViewerLayoutMode/);
assert.match(app, /function renderViewerScrollPages\(\)/);
assert.match(app, /function loadViewerScrollWindow\(centerPage\)/);
assert.match(app, /for \(let page = Math\.max\(1, center - 2\); page <= Math\.min\(state\.catalog\.pages, center \+ 2\); page \+= 1\)/);
assert.match(app, /function handleViewerScrollPagesScroll\(\)/);
assert.match(app, /viewerScrollPages\?\.addEventListener\("scroll", handleViewerScrollPagesScroll, \{ passive: true \}\)/);
assert.match(app, /scrollToPage: isScrollViewerMode\(\)/);
assert.match(app, /const VIEWER_SCROLL_MULTI_COMMAND_WINDOW_MS = 260;/);
assert.match(app, /const VIEWER_SCROLL_WHEEL_FIRST_PAGE_DELTA_PX = 20;/);
assert.match(app, /const VIEWER_SCROLL_WHEEL_PAGE_DELTA_PX = 100;/);
assert.match(app, /const VIEWER_SCROLL_WHEEL_SETTLE_MS = 150;/);
assert.doesNotMatch(app, /VIEWER_SCROLL_WHEEL_ELASTIC_RATIO|elasticRemainder/);
assert.match(app, /viewerScrollLastCommandAt: 0/);
assert.match(app, /viewerScrollWheelAccumulator: 0/);
assert.match(app, /viewerScrollWheelBasePage: 0/);
assert.match(app, /viewerScrollWheelTargetPage: 0/);
assert.match(app, /viewerScrollWheelSettleTimer: 0/);
assert.match(app, /function shouldJumpViewerScrollCommand\(options = \{\}\)/);
assert.match(app, /options\.repeated \|\| isRapidFollowUp \|\| state\.viewerScrollTargetPage/);
assert.match(app, /function scrollViewerByViewport\(direction, options = \{\}\)/);
assert.match(app, /const basePage = state\.viewerScrollTargetPage \|\| state\.page;/);
assert.match(app, /scrollViewerToPage\(targetPage, \{[\s\S]*?behavior: jumpImmediately \? "auto" : "smooth",[\s\S]*?animate: jumpImmediately[\s\S]*?\}\)/);
assert.match(app, /scrollViewerByViewport\(1, \{ repeated: event\.repeat \}\)/);
assert.match(app, /scrollViewerByViewport\(-1, \{ repeated: event\.repeat \}\)/);
assert.match(app, /\["ArrowDown", "PageDown"\]\.includes\(event\.key\)/);
assert.match(app, /\["ArrowUp", "PageUp"\]\.includes\(event\.key\)/);
assert.match(app, /event\.key === "ArrowRight"\)[\s\S]*?event\.preventDefault\(\);[\s\S]*?moveLightbox\(-1\)/);
assert.match(app, /event\.key === "ArrowLeft"\)[\s\S]*?event\.preventDefault\(\);[\s\S]*?moveLightbox\(1\)/);
assert.match(app, /getZoomSurfaceName\(surface\)[\s\S]*?surface === els\.viewerScrollPages && isScrollViewerMode\(\)/);
assert.match(app, /function isActiveZoomSurface\(surface\)\s*\{[\s\S]*?Boolean\(getZoomSurfaceName\(surface\)\)/);
assert.match(app, /attachZoomSurfaceGestures\(els\.viewerScrollPages\)/);
assert.match(app, /const VIEWER_PAGE_SWIPE_MIN_DISTANCE = 46;/);
assert.match(app, /const VIEWER_PAGE_SWAP_CLEANUP_MS = 240;/);
assert.match(app, /function handleViewerPageSwipe\(event, startedX, startedY\)/);
assert.match(app, /isViewerScrollIsolatedZoom\(\) \|\| !isTouchLikePointer\(event\)/);
assert.match(app, /function handleViewerPageSwipe\(event, startedX, startedY\)[\s\S]*?moveLightbox\(direction\);/);
assert.doesNotMatch(app, /function handleViewerPageSwipe\(event, startedX, startedY\)[\s\S]*?scrollViewerByViewport\(direction\)/);
assert.match(app, /function runViewerPageSwapAnimation\(element, options = \{\}\)/);
assert.match(app, /root\?\.querySelectorAll\?\.\("\.page-swap-enter"\)[\s\S]*?element\.classList\.add\("page-swap-enter"\)/);
assert.match(app, /runSingleImageSwapAnimation\(\)[\s\S]*?runViewerPageSwapAnimation\(els\.lightboxImageFrame/);
assert.match(app, /runViewerScrollPageSwapAnimation\(page\)[\s\S]*?runViewerPageSwapAnimation\(frame/);
assert.match(app, /function handleZoomSurfaceDoubleClick\(event\)[\s\S]*?event\.stopPropagation\(\);[\s\S]*?toggleZoomAtPoint/);
assert.match(app, /function getViewerScrollZoomAnchor\(clientX = null, clientY = null\)/);
assert.match(app, /function applyViewerScrollZoom\(anchor = null, options = \{\}\)/);
assert.match(app, /function isViewerScrollIsolatedZoom\(\)/);
assert.match(app, /function enterViewerScrollIsolatedZoom\(nextZoom, focalClientX = null, focalClientY = null\)/);
assert.match(app, /function exitViewerScrollIsolatedZoom\(options = \{\}\)/);
assert.match(app, /function panViewerScrollIsolatedZoomByWheel\(deltaX = 0, deltaY = 0\)/);
assert.match(app, /const remainingDeltaY = safeDeltaY - consumedDeltaY;/);
assert.match(app, /const hasVerticalExitIntent = Math\.abs\(safeDeltaY\) > Math\.abs\(safeDeltaX\) \* 0\.5;/);
assert.match(app, /if \(nextPage === state\.page\) return;/);
assert.match(app, /zoom > AUTO_VIEWER_ZOOM \+ 0\.001/);
assert.match(app, /const zoom = Math\.min\(AUTO_VIEWER_ZOOM, getSafeViewerZoom\(\)\)/);
assert.match(app, /container\.scrollTop = top;/);
assert.match(app, /function getViewerScrollPagePosition\(page\)[\s\S]*?left: Math\.max\(0, frame\.offsetLeft \+ \(frame\.offsetWidth - container\.clientWidth\) \/ 2\)/);
assert.match(app, /function clearViewerScrollWheelGesture\(\)/);
assert.match(app, /function settleViewerScrollWheelGesture\(\)/);
assert.match(app, /function normalizeViewerScrollWheelDelta\(event\)/);
assert.match(app, /function getViewerScrollWheelRequestedSteps\(accumulator\)/);
assert.match(app, /magnitude < VIEWER_SCROLL_WHEEL_FIRST_PAGE_DELTA_PX/);
assert.match(app, /Math\.trunc\(magnitude \/ VIEWER_SCROLL_WHEEL_PAGE_DELTA_PX\)/);
assert.match(app, /Math\.sign\(signedAccumulator\) \* Math\.max\(1, wholePageSteps\)/);
assert.match(app, /function handleViewerScrollWheel\(event\)/);
assert.match(app, /getViewerScrollWheelRequestedSteps\([\s\S]*?viewerScrollWheelAccumulator/);
assert.match(app, /state\.viewerScrollWheelBasePage \+ requestedSteps/);
assert.match(app, /const gestureStarted = !state\.viewerScrollWheelBasePage;/);
assert.match(app, /if \(gestureStarted \|\| targetPage !== previousTargetPage\) \{[\s\S]*?container\.scrollTop = position\.top;[\s\S]*?container\.scrollLeft = position\.left;/);
assert.match(app, /function settleViewerScrollWheelGesture\(\)[\s\S]*?scrollViewerToPage\(targetPage\);/);
assert.match(app, /viewerScrollWheelSettleTimer = window\.setTimeout\([\s\S]*?settleViewerScrollWheelGesture,[\s\S]*?VIEWER_SCROLL_WHEEL_SETTLE_MS/);
assert.match(app, /if \(isScrollViewerMode\(\)\) \{[\s\S]*?handleViewerScrollWheel\(event\);[\s\S]*?return;/);
assert.match(app, /function runViewerScrollPageSwapAnimation\(page\)/);
assert.match(app, /runViewerScrollPageSwapAnimation\(page\)[\s\S]*?timerKey: "viewerScrollPageAnimationTimer"[\s\S]*?root: els\.viewerScrollPages/);
assert.match(app, /if \(options\.animate\) runViewerScrollPageSwapAnimation\(targetPage\);/);
assert.doesNotMatch(app, /if \(options\.animate\) requestAnimationFrame\(\(\) => runViewerScrollPageSwapAnimation/);
assert.match(app, /data-scroll-base-width="\$\{layout\.width\}"[\s\S]*?--viewer-scroll-page-width:\$\{width\}px;--viewer-scroll-page-height:\$\{height\}px/);
assert.match(app, /const viewportWidth = container\?\.clientWidth[\s\S]*?els\.stageCanvas\?\.clientWidth[\s\S]*?window\.innerWidth/);
assert.match(app, /const containerStyle = container \? window\.getComputedStyle\(container\) : null;/);
assert.match(app, /const availableHeight = Math\.max\(220, viewportHeight - verticalInset \* 2\);/);
assert.match(app, /if \(preservePage && !zoomAnchor\) \{[\s\S]*?scrollViewerToPage\(currentPage, \{ behavior: "auto" \}\);/);
assert.match(app, /const positionActivePage = \(\) => scrollViewerToPage\(state\.page, \{[\s\S]*?animate: animateScrollPage[\s\S]*?if \(scrollBehavior === "smooth"\) requestAnimationFrame\(positionActivePage\);[\s\S]*?else positionActivePage\(\);/);
assert.match(app, /updateLightbox\(\{[\s\S]*?scrollToPage: isScrollViewerMode\(\)[\s\S]*?scrollBehavior: "auto"/);
assert.match(app, /const showButton = Boolean\(state\.lightboxOpen && !isAutoViewerZoom\(\)\)/);

assert.match(css, /\.viewer-control-separator\s*\{/);
assert.doesNotMatch(css, /viewer-layout-toggle|viewer-layout-icon/);
assert.match(css, /\.viewer-scroll-pages\s*\{[\s\S]*?overflow-x:\s*auto;[\s\S]*?overflow-y:\s*auto;/);
assert.match(css, /\.viewer-scroll-pages\s*\{[\s\S]*?touch-action:\s*pan-y;/);
assert.doesNotMatch(css, /viewer-wheel-gesture-active/);
assert.match(css, /\.viewer-scroll-page\s*\{[\s\S]*?scroll-snap-align:\s*center;/);
assert.match(css, /\.viewer-scroll-page\s*\{[\s\S]*?width:\s*var\(--viewer-scroll-page-width/);
assert.doesNotMatch(css, /var\(--viewer-scroll-page-width,\s*280px\)|var\(--viewer-scroll-page-height,\s*200px\)/);
assert.match(css, /\.lightbox\.viewer-layout-scroll \.stage-canvas\s*\{[\s\S]*?touch-action:\s*pan-y;/);
assert.match(css, /\.lightbox\.viewer-layout-scroll\.viewer-scroll-zoom-isolated \.viewer-scroll-pages\s*\{[\s\S]*?visibility:\s*hidden;/);
assert.match(css, /\.viewer-scroll-page\.page-swap-enter\s*\{[\s\S]*?z-index:\s*3;/);
assert.match(css, /\.viewer-scroll-page\.page-swap-enter,\s*\.lightbox-image-frame\.page-swap-enter\s*\{[\s\S]*?animation:\s*viewer-page-swap-enter/);
assert.match(css, /@keyframes viewer-page-swap-enter\s*\{[\s\S]*?opacity:\s*var\(--image-swap-start-opacity\);[\s\S]*?filter:\s*blur\(1\.5px\) brightness\(\.94\);[\s\S]*?scale:\s*\.988;/);
assert.doesNotMatch(css, /@keyframes (?:viewer-scroll-page-swap|lightbox-page-swap)/);
assert.doesNotMatch(css, /\.lightbox\.viewer-layout-scroll \.viewer-zoom-indicator\s*\{[\s\S]*?display:\s*none/);

console.log('viewer_scroll_mode_contract.test.js: PASS');
