#!/usr/bin/env python3
"""Synchronize the standalone catalog image viewer with generated catalog metadata.

The viewer is intentionally a single self-contained HTML file so it can be opened
through file:// or a local HTTP server. Catalog metadata is embedded into the file,
while image bytes are always requested from the configured Cloudflare R2/CDN base URL.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

VIEWER_RELATIVE_PATH = Path("catalog-big-pages-viewer-netfree/catalog-big-pages-viewer.html")
README_RELATIVE_PATH = Path("catalog-big-pages-viewer-netfree/README.txt")
CATALOGS_RELATIVE_PATH = Path("catalogs.generated.json")
ASSET_BASE_URL = "https://cdn.bargig-furniture.com/"
SNAPSHOT_START = "    // BEGIN GENERATED CATALOG SNAPSHOT"
SNAPSHOT_END = "    // END GENERATED CATALOG SNAPSHOT"
README_STATS_START = "# BEGIN GENERATED CATALOG STATS"
README_STATS_END = "# END GENERATED CATALOG STATS"
CATALOG_FIELDS = (
    "id",
    "title",
    "description",
    "category",
    "subcategory",
    "pages",
    "dir",
    "cover",
    "imageExt",
    "assetVersion",
    "imageVariants",
    "pageSizes",
)


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def load_catalogs(root: Path) -> list[dict[str, Any]]:
    path = root / CATALOGS_RELATIVE_PATH
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Generated catalog metadata is missing: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Generated catalog metadata is invalid JSON: {path}: {exc}") from exc

    if not isinstance(payload, list):
        raise ValueError(f"Generated catalog metadata must be a JSON array: {path}")

    catalogs: list[dict[str, Any]] = []
    for index, raw in enumerate(payload, start=1):
        if not isinstance(raw, dict):
            raise ValueError(f"Catalog #{index} is not an object")
        catalog_id = str(raw.get("id") or "").strip()
        title = str(raw.get("title") or "").strip()
        directory = str(raw.get("dir") or "").strip().strip("/")
        try:
            pages = int(raw.get("pages") or 0)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Catalog {catalog_id or index} has an invalid pages value") from exc
        if not catalog_id or not title or not directory or pages < 1:
            raise ValueError(
                f"Catalog {catalog_id or index} must contain a non-empty id, title, dir and positive pages count"
            )

        item = {key: raw[key] for key in CATALOG_FIELDS if key in raw}
        item["id"] = catalog_id
        item["title"] = title
        item["dir"] = directory
        item["pages"] = pages
        catalogs.append(item)

    return catalogs


def replace_generated_block(text: str, start_marker: str, end_marker: str, replacement: str) -> str:
    start = text.find(start_marker)
    end = text.find(end_marker)
    if start < 0 or end < 0 or end < start:
        raise ValueError(f"Missing generated block markers: {start_marker!r} / {end_marker!r}")
    end += len(end_marker)
    return text[:start] + replacement + text[end:]


def catalog_snapshot_block(catalogs: list[dict[str, Any]]) -> str:
    payload = json.dumps(catalogs, ensure_ascii=False, indent=2)
    return (
        f"{SNAPSHOT_START}\n"
        "    // Generated by tools/build_big_pages_viewer.py from catalogs.generated.json.\n"
        "    // Do not edit the embedded catalog list manually.\n"
        f"    window.BARGIG_CATALOG_ASSET_BASE_URL = {json.dumps(ASSET_BASE_URL)};\n"
        f"    window.BARGIG_CATALOGS = {payload};\n"
        f"{SNAPSHOT_END}"
    )


def readme_stats_block(catalogs: list[dict[str, Any]]) -> str:
    total_images = sum(int(catalog["pages"]) for catalog in catalogs)
    chunks = (total_images + 49) // 50
    return (
        f"{README_STATS_START}\n"
        f"- מספר קטלוגים: {len(catalogs)}\n"
        f"- סך תמונות/עמודים בכל גודל: {total_images}\n"
        f"- מספר קבוצות של עד 50 תמונות: {chunks}\n"
        f"{README_STATS_END}"
    )


def render_updated_files(root: Path) -> tuple[str, str | None]:
    catalogs = load_catalogs(root)
    viewer_path = root / VIEWER_RELATIVE_PATH
    if not viewer_path.is_file():
        raise FileNotFoundError(f"Standalone viewer is missing: {viewer_path}")
    viewer_text = viewer_path.read_text(encoding="utf-8")
    viewer_text = replace_generated_block(
        viewer_text,
        SNAPSHOT_START,
        SNAPSHOT_END,
        catalog_snapshot_block(catalogs),
    )

    readme_path = root / README_RELATIVE_PATH
    readme_text: str | None = None
    if readme_path.is_file():
        readme_text = replace_generated_block(
            readme_path.read_text(encoding="utf-8"),
            README_STATS_START,
            README_STATS_END,
            readme_stats_block(catalogs),
        )
    return viewer_text, readme_text


def build_big_pages_viewer(root: Path | None = None, *, check: bool = False) -> bool:
    root = (root or project_root()).resolve()
    viewer_path = root / VIEWER_RELATIVE_PATH
    readme_path = root / README_RELATIVE_PATH
    viewer_text, readme_text = render_updated_files(root)

    stale: list[Path] = []
    if viewer_path.read_text(encoding="utf-8") != viewer_text:
        stale.append(viewer_path)
    if readme_text is not None and readme_path.read_text(encoding="utf-8") != readme_text:
        stale.append(readme_path)

    if check:
        if stale:
            relative = ", ".join(path.relative_to(root).as_posix() for path in stale)
            raise RuntimeError(
                "Standalone catalog viewer is stale. Run: python tools/build_big_pages_viewer.py "
                f"(outdated: {relative})"
            )
        return False

    if viewer_path in stale:
        viewer_path.write_text(viewer_text, encoding="utf-8")
    if readme_text is not None and readme_path in stale:
        readme_path.write_text(readme_text, encoding="utf-8")
    return bool(stale)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Synchronize the standalone R2 catalog image viewer.")
    parser.add_argument("--check", action="store_true", help="Fail instead of writing when the viewer is stale")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        changed = build_big_pages_viewer(check=args.check)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if args.check:
        print("Standalone catalog viewer is current.")
    elif changed:
        print(f"Updated: {VIEWER_RELATIVE_PATH.as_posix()}")
        print(f"Updated: {README_RELATIVE_PATH.as_posix()}")
    else:
        print("Standalone catalog viewer is already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
