#!/usr/bin/env python3
"""Verify every catalog page and thumbnail on the public R2/CDN endpoint.

This is a publication gate, not a local build prerequisite. It checks the exact
paths generated by catalogs.generated.json and fails when any object is missing,
empty, or served with a non-image Content-Type.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Sequence

DEFAULT_BASE_URL = "https://cdn.bargig-furniture.com/"
DEFAULT_TIMEOUT = 12.0
DEFAULT_WORKERS = 12


@dataclass(frozen=True)
class AssetCheckResult:
    url: str
    ok: bool
    reason: str = ""
    status: int = 0


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def normalize_base_url(value: str) -> str:
    raw = str(value or "").strip()
    if not raw.startswith(("https://", "http://")):
        raise ValueError("Remote asset URL must start with https:// or http://")
    return raw if raw.endswith("/") else f"{raw}/"


def load_catalogs(path: Path) -> list[dict]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Catalog metadata is missing: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Catalog metadata is invalid JSON: {path}: {exc}") from exc
    if not isinstance(payload, list) or not payload:
        raise ValueError(f"Catalog metadata must contain a non-empty list: {path}")
    return [item for item in payload if isinstance(item, dict)]


def iter_expected_asset_paths(catalogs: Iterable[dict]) -> Iterable[str]:
    seen: set[str] = set()
    for catalog in catalogs:
        catalog_id = str(catalog.get("id") or "").strip() or "unknown"
        directory = str(catalog.get("dir") or "").strip().strip("/")
        extension = str(catalog.get("imageExt") or "webp").strip().lstrip(".") or "webp"
        try:
            pages = int(catalog.get("pages") or 0)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Catalog {catalog_id} has an invalid pages value") from exc
        if not directory or pages < 1:
            raise ValueError(f"Catalog {catalog_id} is missing a valid image directory/pages count")

        for page in range(1, pages + 1):
            filename = f"page-{page:03d}.{extension}"
            for relative in (f"{directory}/{filename}", f"{directory}/thumbs/{filename}"):
                if relative not in seen:
                    seen.add(relative)
                    yield relative


def build_asset_urls(catalogs: Iterable[dict], base_url: str) -> list[str]:
    base = normalize_base_url(base_url)
    return [urllib.parse.urljoin(base, path) for path in iter_expected_asset_paths(catalogs)]


def _response_result(url: str, response) -> AssetCheckResult:
    status = int(getattr(response, "status", 200) or 200)
    content_type = str(response.headers.get("Content-Type", "")).split(";", 1)[0].strip().lower()
    content_length = str(response.headers.get("Content-Length", "")).strip()
    if status not in (200, 206):
        return AssetCheckResult(url, False, f"HTTP {status}", status)
    if not content_type.startswith("image/"):
        return AssetCheckResult(url, False, f"unexpected Content-Type {content_type or '(missing)'}", status)
    if content_length.isdigit() and int(content_length) <= 0:
        return AssetCheckResult(url, False, "empty object", status)
    return AssetCheckResult(url, True, status=status)


def check_asset(
    url: str,
    timeout: float = DEFAULT_TIMEOUT,
    opener: Callable = urllib.request.urlopen,
) -> AssetCheckResult:
    headers = {"Accept": "image/avif,image/webp,image/*,*/*;q=0.5", "User-Agent": "bargig-r2-publication-gate/1.0"}
    head = urllib.request.Request(url, headers=headers, method="HEAD")
    try:
        with opener(head, timeout=timeout) as response:
            return _response_result(url, response)
    except urllib.error.HTTPError as exc:
        if exc.code not in (403, 405, 501):
            return AssetCheckResult(url, False, f"HTTP {exc.code}", exc.code)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return AssetCheckResult(url, False, f"network error: {getattr(exc, 'reason', exc)}")

    # Some object stores disable HEAD while allowing reads. Request one byte so
    # verification remains cheap and does not download large catalog pages.
    get = urllib.request.Request(url, headers={**headers, "Range": "bytes=0-0"}, method="GET")
    try:
        with opener(get, timeout=timeout) as response:
            return _response_result(url, response)
    except urllib.error.HTTPError as exc:
        return AssetCheckResult(url, False, f"HTTP {exc.code}", exc.code)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return AssetCheckResult(url, False, f"network error: {getattr(exc, 'reason', exc)}")


def verify_remote_assets(
    catalogs: Iterable[dict],
    base_url: str,
    *,
    workers: int = DEFAULT_WORKERS,
    timeout: float = DEFAULT_TIMEOUT,
    checker: Callable[[str, float], AssetCheckResult] = check_asset,
) -> tuple[int, list[AssetCheckResult]]:
    urls = build_asset_urls(catalogs, base_url)
    failures: list[AssetCheckResult] = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, workers)) as executor:
        futures = {executor.submit(checker, url, timeout): url for url in urls}
        for future in concurrent.futures.as_completed(futures):
            url = futures[future]
            try:
                result = future.result()
            except Exception as exc:  # Publication must fail closed on checker defects.
                result = AssetCheckResult(url, False, f"verification error: {exc}")
            if not result.ok:
                failures.append(result)
    failures.sort(key=lambda item: item.url)
    return len(urls), failures


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalogs", default="catalogs.generated.json", help="Generated catalog metadata JSON")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help="Public R2/CDN base URL")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS, help="Concurrent checks")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT, help="Timeout per request in seconds")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    root = project_root()
    catalogs_path = Path(args.catalogs)
    if not catalogs_path.is_absolute():
        catalogs_path = root / catalogs_path
    try:
        catalogs = load_catalogs(catalogs_path)
        total, failures = verify_remote_assets(
            catalogs,
            args.base_url,
            workers=max(1, int(args.workers)),
            timeout=max(1.0, float(args.timeout)),
        )
        if failures:
            print(f"ERROR: {len(failures)} of {total} required catalog image assets failed verification.", file=sys.stderr)
            for failure in failures[:50]:
                print(f"  - {failure.url}: {failure.reason}", file=sys.stderr)
            if len(failures) > 50:
                print(f"  ... and {len(failures) - 50} additional failures", file=sys.stderr)
            return 1
        print(f"Remote catalog asset verification passed: {total} page/thumbnail objects.")
        return 0
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
