#!/usr/bin/env python3
"""Verify active catalog image tiers on the public R2/CDN endpoint.

This is a publication gate, not a local build prerequisite. It checks the exact
paths generated by catalogs.generated.json and fails when any object is missing,
empty, or served with a non-image Content-Type. The CLI follows the checked-in
runtime delivery policy; ``--all-tiers`` additionally audits dormant medium files.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable, Sequence

from catalog_image_policy import load_catalog_image_delivery_mode, runtime_uses_medium_images

DEFAULT_BASE_URL = "https://cdn.bargig-furniture.com/"
DEFAULT_TIMEOUT = 12.0
DEFAULT_WORKERS = 12
DEFAULT_RETRIES = 3
DEFAULT_RETRY_WORKERS = 4
DEFAULT_RETRY_DELAY = 0.5
DEFAULT_MAX_TOLERATED_TRANSIENT_FAILURES = 50
DEFAULT_MAX_TOLERATED_TRANSIENT_RATIO = 0.02
CATALOG_ASSET_URL_SCHEMA_VERSION = 2
TRANSIENT_HTTP_STATUSES = frozenset({408, 425, 429, 500, 502, 503, 504})


@dataclass(frozen=True)
class AssetReference:
    path: str
    tier: str
    version: str


@dataclass(frozen=True)
class AssetCheckResult:
    url: str
    ok: bool
    reason: str = ""
    status: int = 0


def is_transient_failure(result: AssetCheckResult) -> bool:
    if result.ok:
        return False
    if result.status in TRANSIENT_HTTP_STATUSES:
        return True
    return result.reason.startswith("network error:")


def split_failures(
    failures: Iterable[AssetCheckResult],
) -> tuple[list[AssetCheckResult], list[AssetCheckResult]]:
    hard: list[AssetCheckResult] = []
    transient: list[AssetCheckResult] = []
    for failure in failures:
        (transient if is_transient_failure(failure) else hard).append(failure)
    return hard, transient


def can_tolerate_transient_failures(
    total: int,
    failures: Sequence[AssetCheckResult],
    *,
    max_failures: int = DEFAULT_MAX_TOLERATED_TRANSIENT_FAILURES,
    max_ratio: float = DEFAULT_MAX_TOLERATED_TRANSIENT_RATIO,
) -> bool:
    if total <= 0 or not failures:
        return False
    return len(failures) <= max(0, int(max_failures)) and (len(failures) / total) <= max(0.0, float(max_ratio))


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def normalize_base_url(value: str) -> str:
    raw = str(value or "").strip()
    if not raw.startswith(("https://", "http://")):
        raise ValueError("Remote asset URL must start with https:// or http://")
    return raw if raw.endswith("/") else f"{raw}/"


def load_catalogs(path: Path) -> list[dict]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8-sig"))
    except FileNotFoundError as exc:
        raise FileNotFoundError(f"Catalog metadata is missing: {path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Catalog metadata is invalid JSON: {path}: {exc}") from exc
    if not isinstance(payload, list) or not payload:
        raise ValueError(f"Catalog metadata must contain a non-empty list: {path}")
    return [item for item in payload if isinstance(item, dict)]


def catalog_asset_version_for_tier(catalog: dict, tier: str) -> str:
    normalized_tier = str(tier or "full").strip() or "full"
    variants = catalog.get("imageVariants") if isinstance(catalog.get("imageVariants"), dict) else {}
    variant = variants.get(normalized_tier) if isinstance(variants.get(normalized_tier), dict) else {}
    base_version = str(variant.get("version") or catalog.get("assetVersion") or "").strip()
    if not base_version:
        return ""
    return f"{base_version}-{normalized_tier}-u{CATALOG_ASSET_URL_SCHEMA_VERSION}"


def iter_expected_asset_references(
    catalogs: Iterable[dict],
    *,
    include_medium: bool = True,
) -> Iterable[AssetReference]:
    seen: set[str] = set()
    for catalog in catalogs:
        catalog_id = str(catalog.get("id") or "").strip() or "unknown"
        directory = str(catalog.get("dir") or "").strip().strip("/")
        extension = str(catalog.get("imageExt") or "webp").strip().lstrip(".") or "webp"
        try:
            pages = int(catalog.get("pages") or 0)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Catalog {catalog_id} has an invalid pages value") from exc
        if not directory or pages < 1:
            raise ValueError(f"Catalog {catalog_id} is missing a valid image directory/pages count")

        variants = catalog.get("imageVariants") if isinstance(catalog.get("imageVariants"), dict) else {}
        medium = variants.get("medium") if isinstance(variants.get("medium"), dict) else None
        medium_directory = str((medium or {}).get("directory") or "").strip().strip("/")

        for page in range(1, pages + 1):
            filename = f"page-{page:03d}.{extension}"
            relatives: list[tuple[str, str]] = [(f"{directory}/{filename}", "full")]
            if include_medium and medium_directory:
                relatives.append((f"{directory}/{medium_directory}/{filename}", "medium"))
            relatives.append((f"{directory}/thumbs/{filename}", "thumb"))
            for relative, tier in relatives:
                if relative in seen:
                    continue
                seen.add(relative)
                yield AssetReference(relative, tier, catalog_asset_version_for_tier(catalog, tier))


def iter_expected_asset_paths(catalogs: Iterable[dict], *, include_medium: bool = True) -> Iterable[str]:
    for reference in iter_expected_asset_references(catalogs, include_medium=include_medium):
        yield reference.path


def append_asset_version(url: str, version: str) -> str:
    value = str(version or "").strip()
    if not value:
        return url
    parsed = urllib.parse.urlsplit(url)
    query = urllib.parse.parse_qsl(parsed.query, keep_blank_values=True)
    query = [(key, item) for key, item in query if key != "v"]
    query.append(("v", value))
    return urllib.parse.urlunsplit(parsed._replace(query=urllib.parse.urlencode(query)))


def build_asset_urls(
    catalogs: Iterable[dict],
    base_url: str,
    *,
    versioned: bool = False,
    include_medium: bool = True,
) -> list[str]:
    base = normalize_base_url(base_url)
    urls: list[str] = []
    for reference in iter_expected_asset_references(catalogs, include_medium=include_medium):
        url = urllib.parse.urljoin(base, reference.path)
        urls.append(append_asset_version(url, reference.version) if versioned else url)
    return urls


def _response_result(url: str, response) -> AssetCheckResult:
    status = int(getattr(response, "status", 200) or 200)
    content_type = str(response.headers.get("Content-Type", "")).split(";", 1)[0].strip().lower()
    content_length = str(response.headers.get("Content-Length", "")).strip()
    if status not in (200, 206):
        return AssetCheckResult(url, False, f"HTTP {status}", status)
    if not content_type.startswith("image/"):
        return AssetCheckResult(url, False, f"unexpected Content-Type {content_type or '(missing)'}", status)
    if content_length.isdigit() and int(content_length) <= 0:
        return AssetCheckResult(url, False, "empty object", status)
    return AssetCheckResult(url, True, status=status)


def check_asset(
    url: str,
    timeout: float = DEFAULT_TIMEOUT,
    opener: Callable = urllib.request.urlopen,
) -> AssetCheckResult:
    headers = {"Accept": "image/avif,image/webp,image/*,*/*;q=0.5", "User-Agent": "bargig-r2-publication-gate/1.0"}
    head = urllib.request.Request(url, headers=headers, method="HEAD")
    try:
        with opener(head, timeout=timeout) as response:
            return _response_result(url, response)
    except urllib.error.HTTPError as exc:
        if exc.code not in (403, 405, 501):
            return AssetCheckResult(url, False, f"HTTP {exc.code}", exc.code)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return AssetCheckResult(url, False, f"network error: {getattr(exc, 'reason', exc)}")

    # Some object stores disable HEAD while allowing reads. Request one byte so
    # verification remains cheap and does not download large catalog pages.
    get = urllib.request.Request(url, headers={**headers, "Range": "bytes=0-0"}, method="GET")
    try:
        with opener(get, timeout=timeout) as response:
            return _response_result(url, response)
    except urllib.error.HTTPError as exc:
        return AssetCheckResult(url, False, f"HTTP {exc.code}", exc.code)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return AssetCheckResult(url, False, f"network error: {getattr(exc, 'reason', exc)}")


def check_asset_via_range_get(
    url: str,
    timeout: float = DEFAULT_TIMEOUT,
    opener: Callable = urllib.request.urlopen,
) -> AssetCheckResult:
    """Verify the normal CDN cache key while transferring at most one byte.

    Do not send a client cache-bypass directive here: the publication gate must
    observe the same cached status a regular browser request would receive.
    """
    headers = {
        "Accept": "image/avif,image/webp,image/*,*/*;q=0.5",
        "Range": "bytes=0-0",
        "User-Agent": "bargig-r2-versioned-publication-gate/1.0",
    }
    request = urllib.request.Request(url, headers=headers, method="GET")
    try:
        with opener(request, timeout=timeout) as response:
            return _response_result(url, response)
    except urllib.error.HTTPError as exc:
        return AssetCheckResult(url, False, f"HTTP {exc.code}", exc.code)
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return AssetCheckResult(url, False, f"network error: {getattr(exc, 'reason', exc)}")


def verify_remote_assets(
    catalogs: Iterable[dict],
    base_url: str,
    *,
    workers: int = DEFAULT_WORKERS,
    timeout: float = DEFAULT_TIMEOUT,
    checker: Callable[[str, float], AssetCheckResult] = check_asset,
    versioned: bool = False,
    include_medium: bool = True,
    retries: int = DEFAULT_RETRIES,
    retry_workers: int = DEFAULT_RETRY_WORKERS,
    retry_delay: float = DEFAULT_RETRY_DELAY,
    sleeper: Callable[[float], None] = time.sleep,
) -> tuple[int, list[AssetCheckResult]]:
    urls = build_asset_urls(
        catalogs,
        base_url,
        versioned=versioned,
        include_medium=include_medium,
    )
    results: dict[str, AssetCheckResult] = {}

    def run_checks(target_urls: Sequence[str], worker_count: int) -> None:
        with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, worker_count)) as executor:
            futures = {executor.submit(checker, url, timeout): url for url in target_urls}
            for future in concurrent.futures.as_completed(futures):
                url = futures[future]
                try:
                    result = future.result()
                except Exception as exc:  # Publication must fail closed on checker defects.
                    result = AssetCheckResult(url, False, f"verification error: {exc}")
                results[url] = result

    run_checks(urls, workers)

    retry_count = max(0, int(retries))
    for retry_index in range(retry_count):
        retry_urls = sorted(
            url for url, result in results.items() if is_transient_failure(result)
        )
        if not retry_urls:
            break
        delay = max(0.0, float(retry_delay)) * (2 ** retry_index)
        if delay:
            sleeper(delay)
        run_checks(retry_urls, min(max(1, int(retry_workers)), len(retry_urls)))

    failures = sorted(
        (result for result in results.values() if not result.ok),
        key=lambda item: item.url,
    )
    return len(urls), failures


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalogs", default="catalogs.generated.json", help="Generated catalog metadata JSON")
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL, help="Public R2/CDN base URL")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS, help="Concurrent checks")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT, help="Timeout per request in seconds")
    parser.add_argument("--retries", type=int, default=DEFAULT_RETRIES, help="Retries for transient network/server failures")
    parser.add_argument(
        "--retry-workers",
        type=int,
        default=DEFAULT_RETRY_WORKERS,
        help="Lower concurrency used only for transient-failure retries",
    )
    parser.add_argument(
        "--retry-delay",
        type=float,
        default=DEFAULT_RETRY_DELAY,
        help="Initial retry delay in seconds; later retries use exponential backoff",
    )
    parser.add_argument(
        "--allow-small-transient-network-failures",
        action="store_true",
        help=(
            "Treat a small residual set of network-only failures as inconclusive warnings after retries. "
            "Definite HTTP/content failures still fail the publication gate."
        ),
    )
    parser.add_argument(
        "--versioned",
        action="store_true",
        help="Check the exact cache-busted URLs emitted by the site, not only the origin object paths",
    )
    parser.add_argument(
        "--all-tiers",
        action="store_true",
        help="Verify generated medium assets even when the active runtime policy is full-only",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    root = project_root()
    catalogs_path = Path(args.catalogs)
    if not catalogs_path.is_absolute():
        catalogs_path = root / catalogs_path
    try:
        catalogs = load_catalogs(catalogs_path)
        delivery_mode = load_catalog_image_delivery_mode(root)
        include_medium = bool(args.all_tiers) or runtime_uses_medium_images(delivery_mode)
        checker = check_asset_via_range_get if args.versioned else check_asset
        total, failures = verify_remote_assets(
            catalogs,
            args.base_url,
            workers=max(1, int(args.workers)),
            timeout=max(1.0, float(args.timeout)),
            checker=checker,
            versioned=bool(args.versioned),
            include_medium=include_medium,
            retries=max(0, int(args.retries)),
            retry_workers=max(1, int(args.retry_workers)),
            retry_delay=max(0.0, float(args.retry_delay)),
        )
        if failures:
            hard_failures, transient_failures = split_failures(failures)
            if (
                not hard_failures
                and args.allow_small_transient_network_failures
                and can_tolerate_transient_failures(total, transient_failures)
            ):
                print(
                    "WARNING: "
                    f"{len(transient_failures)} of {total} image URLs remained inconclusive after retries "
                    "because the network connection was interrupted. No definite missing, empty, or invalid "
                    "image response was detected, so publication may continue.",
                    file=sys.stderr,
                )
                for failure in transient_failures[:20]:
                    print(f"  - {failure.url}: {failure.reason}", file=sys.stderr)
                if len(transient_failures) > 20:
                    print(
                        f"  ... and {len(transient_failures) - 20} additional transient failures",
                        file=sys.stderr,
                    )
                return 0
            print(f"ERROR: {len(failures)} of {total} required catalog image assets failed verification.", file=sys.stderr)
            for failure in failures[:50]:
                print(f"  - {failure.url}: {failure.reason}", file=sys.stderr)
            if len(failures) > 50:
                print(f"  ... and {len(failures) - 50} additional failures", file=sys.stderr)
            return 1
        mode = "versioned CDN URLs" if args.versioned else "origin object URLs"
        tiers = "all generated tiers" if include_medium else "active full-only tiers"
        print(f"Remote catalog asset verification passed: {total} {mode} ({tiers}).")
        return 0
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
